# Generated by Django 4.2.2 on 2023-06-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=100)),
                ('pemail', models.CharField(max_length=100)),
                ('pcontact', models.CharField(max_length=100)),
            ],
        ),
    ]
