# Generated by Django 4.2.2 on 2023-06-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_persons'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persons',
            table='persons',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
