# Generated by Django 4.2.2 on 2023-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0003_alter_persons_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(max_length=10),
        ),
    ]
